### ISSUE TITLE
Simplify driver config

### ISSUE THREAD

**Issue by mvar** [ongr-io/CurrencyExchangeBundle#31]
Remove setters support. This is not needed for custom services, only for our `OpenExchangeRatesDriver`. It would be better to add optional config parameter for that.

Config should look like this:

```yml
ongr_currency_exchange:
    # ...
    driver: app.my_currency_driver
```

Or in case of `OpenExchangeRatesDriver`:

```yml
ongr_currency_exchange:
    # ...
    driver: ongr_currency_exchange.open_exchange_driver
    open_exchange_rates_id: XXX
```
